requires 'FindBin';
requires 'Hash::Fold';
requires 'List::UtilsBy';
requires 'Moo';
requires 'Path::Tiny', '0.125';
requires 'Text::CSV_XS';
requires 'WWW::Mechanize';
requires 'Web::Scraper';
requires 'feature';
requires 'lib';
requires 'strict';
requires 'warnings';
